[build]
  command = "composer install --no-dev && composer site-install && find . -depth -type d -name tests -exec rm -r -f '{}' ';' && composer archive --dir=. --file=public/assets/build --format=zip"
[build.environment]
  PHP_VERSION = "8.3"
